module CorbaTest {

    interface Car {
        boolean has_wheels();
        boolean has_windows();
        boolean has_doors();
        boolean has_engine();
        boolean has_brakes();
        boolean has_lights();
        boolean has_steering_wheel();
        boolean has_color();

        boolean add_wheels();
        boolean add_windows();
        boolean add_doors();
        boolean add_engine();
        boolean add_brakes();
        boolean add_lights();
        boolean add_steering_wheel();
        boolean add_color();

        string get_uuid();
    };

    interface CarFactory {
        Car add_car();
        Car get_car(in long index);
        long get_car_count();
    };

};
